name = "NeuralDataScience"
uuid = "cc86e428-61f1-481c-8c8e-23f0d7d18210"
authors = ["Martin Wimpff"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
